version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/mini-project/index.js
      - ./models/user.model.js:/mini-project/backend/models/user.model.js
    ports:
      - 3000:3000
  
  my-database:
    image: mongo:latest
    ports:
      - 27017:27017